spring:
  profiles:
    active: dev

server: 
  port: 8201
spring:   
  profiles: dev #开发环境
  application:
    name: application
eureka:
  client:
    service-url:
      defaultZone: http://192.168.194.130:8761/eureka/,http://192.168.194.131:8761/eureka/
     
server: 
  port: 8202
spring:   
  profiles: test #开发环境
  application:
    name: application
eureka:
  client:
    service-url:
      defaultZone: http://192.168.194.130:8761/eureka/,http://192.168.194.131:8761/eureka/
